baseURL = 'https://blog-nzn.pages.dev/'
languageCode = 'ko-kr'
title = 'Archive & Log'
theme = 'PaperMod'

[pagination]
  pagerSize = 10

[params]
  env = 'production'
  title = 'Archive & Log'
  description = '음악, 기술, 텍스트 아카이브'
  author = 'HOYAN'
  mainSections = ["posts"]
  
  defaultTheme = 'auto'
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true

  [params.homeInfoParams]
    Title = "Archive & Thoughts"
    Content = "작업과 기록, 생각들을 보관하는 개인 아카이브입니다."

[[menu.main]]
  identifier = "posts"
  name = "전체 글"
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "categories"
  name = "카테고리"
  url = "/categories/"
  weight = 20

[[menu.main]]
  identifier = "tags"
  name = "태그"
  url = "/tags/"
  weight = 30
